language: groovy
script:
  - ./gradlew clean build --daemon
  - cd example
  - ../gradlew clean build --daemon
matrix:
  include:
  - os: linux
    jdk: oraclejdk8
  - os: linux
    jdk: oraclejdk9
  - os: osx
    osx_image: xcode9.3beta
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
